"""Proposals — manage the weekly-review improvement proposals.

Each row in the `proposals` table was generated by the Saturday weekly
review. You can flip status between open / accepted / rejected / tested
and optionally record an outcome. Next week's review prompt includes
prior proposals so the loop actually closes.
"""
from __future__ import annotations

from datetime import date
from pathlib import Path

import pandas as pd
import streamlit as st

from tradingagents.dashboard.multi_variant import get_variant_dbs
from tradingagents.storage.database import TradingDatabase


def _fresh_dbs() -> dict:
    """Return fresh TradingDatabase instances so newly-added helper methods
    (e.g. get_proposals) are available. The cached `get_variant_dbs` can
    hold instances from an older class definition after a code edit — fine
    for reads that used existing methods, but breaks for new helpers.
    """
    from tradingagents.testing.ab_config import load_experiment
    import os
    yaml_path = os.getenv("EXPERIMENT_CONFIG_PATH", "experiments/paper_launch_v2.yaml")
    if not Path(yaml_path).exists():
        return {}
    exp = load_experiment(yaml_path)
    out: dict = {}
    for v in exp.variants:
        if v.db_path and Path(v.db_path).exists():
            out[v.name] = TradingDatabase(v.db_path)
    return out


STATUSES = ["open", "accepted", "rejected", "tested"]
STATUS_COLORS = {
    "open": "#90caf9",
    "accepted": "#81c784",
    "rejected": "#e57373",
    "tested": "#ffd54f",
}


st.set_page_config(page_title="Proposals — TradingBot", layout="wide")
st.title("Proposals")

dbs = _fresh_dbs()
if not dbs:
    st.warning("No variant databases found.")
    st.stop()

variant_names = ["All"] + list(dbs.keys())

# ── Sidebar ──────────────────────────────────────────────────────
selected_variant = st.sidebar.selectbox("Variant", variant_names, index=0)
selected_status = st.sidebar.multiselect(
    "Status", STATUSES, default=["open", "accepted"],
)
sort_by = st.sidebar.radio("Sort by", ["Newest first", "Oldest first"], index=0)


# ── Load proposals across variants ───────────────────────────────

def _load_proposals() -> pd.DataFrame:
    frames = []
    target_variants = (
        [selected_variant] if selected_variant != "All" else list(dbs.keys())
    )
    for v in target_variants:
        db = dbs.get(v)
        if db is None:
            continue
        try:
            rows = db.get_proposals(variant=v)
        except Exception as e:
            st.warning(f"Failed to load proposals for {v}: {e}")
            continue
        if rows:
            df = pd.DataFrame(rows)
            df["_db"] = v  # remember which variant's DB to write back to
            frames.append(df)
    if not frames:
        return pd.DataFrame()
    df = pd.concat(frames, ignore_index=True)
    if selected_status:
        df = df[df["status"].isin(selected_status)]
    if sort_by == "Newest first":
        df = df.sort_values("created_at", ascending=False)
    else:
        df = df.sort_values("created_at", ascending=True)
    return df


df = _load_proposals()
if df.empty:
    st.info("No proposals match the current filters. Weekly reviews run Sat 09:00 ET.")
    st.stop()


# ── KPI strip ────────────────────────────────────────────────────
counts = df["status"].value_counts().to_dict()
c1, c2, c3, c4 = st.columns(4)
c1.metric("Open", counts.get("open", 0))
c2.metric("Accepted", counts.get("accepted", 0))
c3.metric("Tested", counts.get("tested", 0))
c4.metric("Rejected", counts.get("rejected", 0))

st.divider()


# ── Proposal rows ────────────────────────────────────────────────

for _, row in df.iterrows():
    title = row.get("title") or "Untitled"
    variant = row.get("variant") or row.get("_db")
    status = row.get("status") or "open"
    color = STATUS_COLORS.get(status, "#ccc")
    iso_week = row.get("iso_week", "")
    pid = int(row["id"])

    expander_label = (
        f"[{variant}] {title}  ·  {iso_week}  ·  {status.upper()}"
    )
    with st.expander(expander_label, expanded=False):
        badge = (
            f"<span style='background:{color};color:#000;padding:2px 8px;"
            f"border-radius:4px;font-size:11px;'>{status.upper()}</span>"
        )
        st.markdown(
            f"{badge} &nbsp; <span style='color:#aaa;font-size:12px;'>"
            f"created {row.get('created_at', '')}</span>",
            unsafe_allow_html=True,
        )

        # Body sections
        def _section(label: str, key: str):
            val = row.get(key)
            if val:
                st.markdown(f"**{label}**")
                st.markdown(val)

        _section("What", "what")
        _section("Why", "why")
        _section("How to validate", "how_to_validate")
        _section("Risk", "risk")

        if row.get("outcome_summary"):
            st.markdown("**Outcome**")
            st.markdown(row["outcome_summary"])

        # Status editor — writes back to the owning variant's DB.
        st.markdown("---")
        ec1, ec2 = st.columns([1, 2])
        with ec1:
            new_status = st.selectbox(
                "Set status",
                STATUSES,
                index=STATUSES.index(status) if status in STATUSES else 0,
                key=f"status_{variant}_{pid}",
            )
        with ec2:
            new_outcome = st.text_area(
                "Outcome summary (optional, only saved on 'tested')",
                value=row.get("outcome_summary") or "",
                key=f"outcome_{variant}_{pid}",
                height=60,
            )

        if st.button("Save", key=f"save_{variant}_{pid}"):
            try:
                dbs[variant].update_proposal_status(
                    pid,
                    status=new_status,
                    outcome_summary=(new_outcome if new_status == "tested" else None),
                )
                st.success(f"Updated → {new_status}")
                st.cache_data.clear()
                st.rerun()
            except Exception as e:
                st.error(f"Failed to save: {e}")
